### ISSUE TITLE
.

### ISSUE THREAD

**Issue by dd01da0465b4542f8f8af4ecedc149ed** [annson24/SXTools#1]

**Comment by ThatNerdyPikachu** [comment]
you agreed to work with tx
either that or they stole it, which is likely

**Comment by Jan200101** [comment]
very professional

**Comment by astronautlevel2** [comment]
![image](https://user-images.githubusercontent.com/7305572/44402068-a0ca1400-a51e-11e8-9f1d-2d244680f1f0.png)
I see you like your own posts :thinking:

Also, on a more serious note, why would you even bother creating this issue? They forked an existing project and made modifications to it that suit their needs, and then shared it back with the community. That should be encouraged, not attacked, especially given they gave proper credit and everything.

**Comment by ghost** [comment]
For someone that dosen't like LGBT flaming and is trans, that's ironic

**Comment by Cyuubi** [comment]
smh my autism kicked in when i made this post, updating and sorry for any inconvenience.

**Comment by DrHacknik** [comment]
Wow, mature human being around here. Apparently name calling is professional around here. And being 'autistic' is no excuse.

**Comment by Cyuubi** [comment]
i will admit that what i did was probably offensive and shouldnt have been done and was highly immature. i was not given enough info, sorry to the person who made this, hopefully things can get sorted out with TX.
